### ISSUE TITLE
Example Datasets doesnt load.

### ISSUE THREAD

**Issue by FfKB** [tchitchek-lab/MDSRefMaps#1]
load("HGA-tissue_data.Rdata")
rror in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'HGA-tissue_data.Rdata', probable reason 'No such file or directory'

**Comment by fbonnardel** [comment]
Fixed by 18f012f

The Rdata file is now available on the ftp server, and the tutorial updated 
`download.file("ftp://ftp.mdsrefmaps.org/public/HGA-TISSUE_data.Rdata", "HGA-tissue_data.rData")`
`load("HGA-tissue_data.Rdata")`
if the file is corrupted, check the firewall or download the file manually
